language: python
cache:
  directories:
    - $HOME/.cache/pip
env:
    global:
        - DEPENDS="numpy scipy sympy matplotlib nibabel"
python:
- 2.6
- 3.2
- 3.3
- 3.4
matrix:
  include:
  - python: 2.7
    env:
    - COVERAGE=--with-coverage
before_install:
- sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran libpng-dev
- pip install --no-index -f http://wheels2.astropy.org -f https://nipy.bic.berkeley.edu/scipy_installers/travis
  scipy matplotlib;
- pip install nibabel
- if [ "${COVERAGE}" == "--with-coverage" ]; then pip install coverage; pip install
  coveralls; fi
install:
- python setup.py install
script:
- mkdir for_testing
- cd for_testing
- if [ "${COVERAGE}" == "--with-coverage" ]; then cp ../.coveragerc .; fi
- $PYTHON ../tools/nipnost $COVERAGE `python -c "import os; import nireg; print(os.path.dirname(nireg.__file__))"`
after_success:
- if [ "${COVERAGE}" == "--with-coverage" ]; then coveralls; fi
deploy:
  provider: pypi
  user: alexis-roche
  password:
    secure: JVVrRUGF+7AZmW92IyVOpyUPsPyZC+3J5I03JHq//kW/GInxojoUsBXeLkXgsVgBrxMKG3KjRrReEl4gRRxF3jN6Sk9fjqCGPXHgRsRYJECUWl+JcJk96uRCgn9BjawVU4gXrw8vQWAuauke0RYFTem+riRgPb5HEoeAzG5TyNaBe9Lip/g+mNUdJXVB35fgDQDisWXBzBwmv5RAr36eB5Q0PzpGzTj80aUeN3PAlvM51HGUtTyQuLQA4ZyMppVkt7+d+nXzefkqMbwbahCglg+K1G0oixdqMuUIpiY2+VbLhgDrynq0uk2JO6enCnmkGJlTzEZyRpPO0UfEAQ2pqcVchnG19O9dAw/QuLPBTaRS53UQkrgwil1n4DTjsUiS+weGQxze13Dt76Duh/Yyou611rxEqHrF0TSlQcACuj5dcOC2Y0SburfxBVzaOto1Bdb2Oc00DF6racePZL4S3Kc0symMm3uNHsok+A7RW/tAylY48n9/pc9hvKiHzzhr4pP1EQJx6DglWUQ+PHw3jOGopbiZpqH8V5Qg1GwXz38uP6ViWXLBj+4VhYp/TriXMO6+b7Ptektsz1U2KS+gPHH/Mtw6fd5YFBNfq0TP7Qq2lZ8/WB7Y6T/ZtNV6cAzh6kwgEmbOd6FgzeaBgYqOxIeE7q+d44+GyF7C75X57QE=
  on:
    tags: true
    branch: master
